version: "3.3"
services:
  jupyter:
    container_name: jupyter_notebook
    build:
      context: ./jupyter-notebooks
    ports:
      - "8888:8888"
    links:
      - "postgres:db"
    depends_on:
      - postgres
    volumes:
      - ./jupyter-notebooks/notebooks:/notebooks

  postgres:
    container_name: postgres_db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db/data:/var/lib/postgresql/data

  dash:
    container_name: dash_app
    restart: always
    build: ./dash
    ports:
      - "8050:8050"
    volumes:
      - ./dash:/dash_app
    depends_on:
      - postgres
    command: python app.py
